name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker version
          # 使用Dockerfile构建镜像
          docker build . --file dockerfile --tag registry.cn-hangzhou.aliyuncs.com/cdyb/alpine-java:openjdk17_cn_slim
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          pwd & ls -al
          # 推送镜像到镜像仓库
          docker push registry.cn-hangzhou.aliyuncs.com/cdyb/alpine-java:openjdk17_cn_slim


